default_language_version:
  python: python3.10

ci:
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit fixed errors you made'
  autoupdate_schedule: quarterly

exclude: 'templates/'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-docstring-first

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Sort imports

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        name: Format code

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: PEP8

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
