[package]
name = "fast_unidecode"
version = "1.0.0"
edition = "2024"
authors = ["Daniel Stancl <daniel.stancl@gmail.com>", "Amit Chowdhury <amitc97@gmail.com>"]
description = "Provides pure ASCII transliterations of Unicode strings."
homepage = "https://github.com/stancld/rust-unidecode/"
repository = "https://github.com/stancld/rust-unidecode/"
readme = "README.md"
keywords = [
  "unidecode",
  "unidecoder",
  "Unicode",
  "ASCII",
  "transliteration"
]
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13"
]
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.htmlAdd commentMore actions
[lib]
name = "fast_unidecode"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.25.1"
features = ["extension-module"]
