name: Build

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pkg-check:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: messense/maturin-action@v1

      - name: Build package with maturin
        run: maturin build --release

  pkg-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11, windows-2022]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: messense/maturin-action@v1

      - name: Build package with maturin
        run: maturin build --release

      - name: Install | Uninstall package
        working-directory: target/wheels/
        run: |
          python -m pip install *.whl
          python -c "import fast_unidecode"
          python -m pip uninstall -y fast_unidecode
