name: PyPI Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches: [master, "pypi-release"]
  pull_request:
    branches: [master]

jobs:
  build_wheels:
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
        os: [ubuntu-20.04, macOS-11, windows-2022]
        python: ["3.8", "3.9", "3.10"]
        architecture: [x86, x64]

  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        architecture:
    - uses: messense/maturin-action@v1

    - name: Build package with maturin
      run: maturin build --release
