name: PyPI Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  builds-wheels-manylinux:
    runs-on: ubuntu-20.04
    name: Build wheels for manilinux
    container: quay.io/pypa/manylinux2010_x86_64
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]

    steps:
      # v1 is required when using manylinux2010
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - uses: messense/maturin-action@v1

      - name: Build Linux package on (${{ matrix.python }})
        run: |
          maturin build --release
          ls -lh target/wheels/

  build-wheels-windows-32bit:
    runs-on: windows-2022
    name: Build wheels for Windows 32bit
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
        rust: [stable]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x86

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-i686-pc-windows-msvc
          override: true

      - uses: messense/maturin-action@v1

      - name: Build Windows package on 32bit (${{ matrix.python }})
        run: |
          maturin build --release
          ls -lh target/wheels/

  build-wheels-windows-64bit:
    runs-on: windows-2022
    name: Build wheels for Windows 64bit
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
        rust: [stable]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: messense/maturin-action@v1

      - name: Build Windows package on 32bit (${{ matrix.python }})
        run: |
          maturin build --release
          ls -lh target/wheels/
