name: PyPI Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches: [master, "pypi-release"]
  pull_request:
    branches: [master]

jobs:
  build-macos-wheels:
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      os: [macOS-11]
      python: ["3.8", "3.9", "3.10"]
      architecture: [x86_64, aarch64]

  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.architecture }}
    - uses: messense/maturin-action@v1

    - name: Build ${{ matrix.os }} package on ${{ matrix.architecture }} (${{ matrix.python }})
      run: |
        maturin build --release
        ls -lh target/wheels/
